apiVersion: extensions/v1beta1
kind: Deployment           
metadata:
  name: order                          
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order                      
    spec:
      containers:                       
      - name: order                     
        image: debajyotim/order             
        ports:
        - containerPort: 8510           
        env:
        - name: EUREKA_URL
          value: "http://eureka:admin@eureka-server:8761/eureka"
          #value: "http://173.193.75.122:30875/eureka"
