apiVersion: extensions/v1beta1
kind: Deployment           
metadata:
  name: status                          
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: status                      
    spec:
      containers:                       
      - name: status                     
        image: debajyotim/status             
        ports:
        - containerPort: 8250           
        env:
        - name: EUREKA_URL
          value: "http://eureka:admin@eureka-server:8761/eureka"
          #value: "http://173.193.75.122:30875/eureka"
